export const metadata = {
  title: "Aurora cars",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ boxSizing: "border-box", margin: 0 }}>{children}</body>
    </html>
  );
}
